# Generated by Django 4.2.16 on 2025-03-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Tickect',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
