# Generated by Django 4.2.16 on 2025-02-19 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('experience', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('on_leave', 'On Leave')], default='available', max_length=20)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_preference', models.CharField(blank=True, choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('van', 'Van'), ('', 'No Preference')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='driver_photos/')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
