# Generated by Django 4.2.16 on 2025-03-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='emergency_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_preference',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('sender_name', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bus_number', models.CharField(max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.driver')),
            ],
        ),
    ]
