# Generated by Django 4.2.16 on 2025-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_driver_date_joined_alter_driver_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='last_service',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='license',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='on_maintainance',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='reported',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
