# Generated by Django 5.1.6 on 2025-08-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_booking_seats_remove_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='photo',
        ),
    ]
